name: Deploy to Cloud Run

on:
  push:
    branches:
      - main    # Change if you deploy from a different branch

env:
  PROJECT_ID: project-7ee9ba0e-6038-467d-83a
  REGION: us-central1
  SERVICE_NAME: my-website-service
  IMAGE_NAME: my-website-image

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/687832097444/locations/global/workloadIdentityPools/github-pool-2/providers/github-provider'
          service_account: 'github-deploy-sa@project-7ee9ba0e-6038-467d-83a.iam.gserviceaccount.com'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker --quiet

      - name: Build container image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push container image
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated
